name: "Deployment of Infra Pipeline"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    environment: dev
    steps:    
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 669b9585-949d-47fc-bad6-15e843d919a8
          tenant-id:  7e203e7f-46ff-4cc1-8e94-c0903765687e
          subscription-id: 42ef39d4-890a-43c3-9c88-fc38b8fb9943
          
      - name: Terraform fmt
        run: terraform fmt -recursive
        working-directory: environments/dev

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: environments/dev
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev
        
  terraform-apply: 
    runs-on: self-hosted
    needs: terraform-init-plan
    environment: dev
    steps:    
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 669b9585-949d-47fc-bad6-15e843d919a8
          tenant-id:  7e203e7f-46ff-4cc1-8e94-c0903765687e
          subscription-id: 42ef39d4-890a-43c3-9c88-fc38b8fb9943

      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev   
          

